apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
spec:
  containers:
  - name: pod-stress-test
    image: m.daocloud.io/docker.io/polinux/stress-ng
    command: [ "/bin/bash", "-c", "--" ]
    # args: [ "stress-ng --all 0 --timeout 1m --metrics" ]
    # args: [ "stress-ng --cpu 1 --vm 1 --fork 8 --timeout 1m --metrics" ]
    # args: [ "stress-ng --cpu 4 --vm 4 --bigheap 4 --vm-bytes 1G --timeout 1m --metrics" ]
    args: [ "stress-ng --taskset 0 --class cpu,cpu-cache,memory,vm --seq 0 --timeout 1m --metrics" ]
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
  nodeName: cn-shenzhen.172.16.1.137